version: '3.0'

expectations:
  population_size: 10000

actions:

  
  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2021-06-01 to 2021-12-01 by month" --output-dir=output --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input_*.csv.gz

  generate_study_population_ethnicity:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_ethnicity --output-dir=output --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input_ethnicity.csv.gz

  join_ethnicity:
    run: cohort-joiner:v0.0.18
      --lhs output/input_*.csv.gz
      --rhs output/input_ethnicity.csv.gz
      --output-dir output/joined
    needs: [generate_study_population, generate_study_population_ethnicity]
    outputs:
      highly_sensitive:
        cohort: output/joined/input*.csv.gz

  generate_study_population_practice_count:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_practice_count --index-date-range "2021-06-01 to 2021-12-01 by month" --output-dir=output/joined --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/joined/input_practice_count_*.csv.gz

  generate_measures:
      run: cohortextractor:latest generate_measures --study-definition study_definition --output-dir=output/joined
      needs: [join_ethnicity]
      outputs:
        moderately_sensitive:
          measure_csv: output/joined/measure_*_rate.csv

  redact_measures:
      run: python:latest python analysis/redact_measures.py
      needs: [generate_measures]
      outputs:
        moderately_sensitive:
          measures: output/joined/measure_*_rat*.csv
  
  generate_top_5_table:
      run: python:latest python analysis/generate_top_5_tables.py
      needs: [redact_measures]
      outputs:
        moderately_sensitive:
          table: output/joined/top_5_code_table.csv

  plot_measures:
      run: python:latest python analysis/plot_measures.py
      needs: [redact_measures]
      outputs:
        moderately_sensitive:
          plots: output/joined/plot_*.png
          decile_chart: output/joined/decile_chart.png
  
  create_notebook:
    run: python:latest python analysis/create_notebook.py
    outputs:
      moderately_sensitive:
        notebook: analysis/SRO_Notebook.ipynb

  generate_notebook:
    run: jupyter:latest jupyter nbconvert /workspace/analysis/SRO_Notebook.ipynb --execute --to html --output-dir=/workspace/output/joined --ExecutePreprocessor.timeout=86400 --no-input
    needs: [create_notebook, generate_study_population_practice_count, generate_top_5_table, plot_measures, redact_measures]
    outputs:
      moderately_sensitive:
        notebook: output/joined/SRO_Notebook.html

  # run_tests:
  #   run: python:latest python -m pytest --junit-xml=output/pytest.xml --verbose
  #   outputs:
  #     moderately_sensitive:
  #       log: output/pytest.xml
